export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          age: number | null;
          height: number | null;
          weight: number | null;
          gender: 'male' | 'female' | 'other' | null;
          dietary_preferences: string[] | null;
          health_goals: string[] | null;
          daily_calorie_target: number | null;
          daily_protein_target: number | null;
          daily_carbs_target: number | null;
          daily_fat_target: number | null;
          weekly_activity_hours: number | null;
          preferred_meal_count: number;
          meal_prep_capacity: 'low' | 'medium' | 'high';
          budget_per_day: number | null;
          avatar_url: string | null;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          age?: number | null;
          height?: number | null;
          weight?: number | null;
          gender?: 'male' | 'female' | 'other' | null;
          dietary_preferences?: string[] | null;
          health_goals?: string[] | null;
          daily_calorie_target?: number | null;
          daily_protein_target?: number | null;
          daily_carbs_target?: number | null;
          daily_fat_target?: number | null;
          weekly_activity_hours?: number | null;
          preferred_meal_count?: number;
          meal_prep_capacity?: 'low' | 'medium' | 'high';
          budget_per_day?: number | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          age?: number | null;
          height?: number | null;
          weight?: number | null;
          gender?: 'male' | 'female' | 'other' | null;
          dietary_preferences?: string[] | null;
          health_goals?: string[] | null;
          daily_calorie_target?: number | null;
          daily_protein_target?: number | null;
          daily_carbs_target?: number | null;
          daily_fat_target?: number | null;
          weekly_activity_hours?: number | null;
          preferred_meal_count?: number;
          meal_prep_capacity?: 'low' | 'medium' | 'high';
          budget_per_day?: number | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      master_meals: {
        Row: {
          id: string;
          name: string;
          description: string;
          category: 'breakfast' | 'lunch' | 'dinner' | 'snack';
          ingredients: string[];
          instructions: string[];
          prep_time_minutes: number;
          cook_time_minutes: number;
          servings: number;
          calories: number;
          protein_grams: number;
          carbs_grams: number;
          fat_grams: number;
          fiber_grams: number;
          cost_usd: number;
          dietary_tags: string[];
          difficulty: 'easy' | 'medium' | 'hard';
          image_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          category: 'breakfast' | 'lunch' | 'dinner' | 'snack';
          ingredients: string[];
          instructions: string[];
          prep_time_minutes: number;
          cook_time_minutes: number;
          servings: number;
          calories: number;
          protein_grams: number;
          carbs_grams: number;
          fat_grams: number;
          fiber_grams: number;
          cost_usd: number;
          dietary_tags: string[];
          difficulty: 'easy' | 'medium' | 'hard';
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          category?: 'breakfast' | 'lunch' | 'dinner' | 'snack';
          ingredients?: string[];
          instructions?: string[];
          prep_time_minutes?: number;
          cook_time_minutes?: number;
          servings?: number;
          calories?: number;
          protein_grams?: number;
          carbs_grams?: number;
          fat_grams?: number;
          fiber_grams?: number;
          cost_usd?: number;
          dietary_tags?: string[];
          difficulty?: 'easy' | 'medium' | 'hard';
          image_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_meal_plans: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          start_date: string;
          end_date: string | null;
          target_calories: number | null;
          target_protein: number | null;
          target_carbs: number | null;
          target_fat: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          start_date: string;
          end_date?: string | null;
          target_calories?: number | null;
          target_protein?: number | null;
          target_carbs?: number | null;
          target_fat?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string | null;
          start_date?: string;
          end_date?: string | null;
          target_calories?: number | null;
          target_protein?: number | null;
          target_carbs?: number | null;
          target_fat?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      daily_logs: {
        Row: {
          id: string;
          user_id: string;
          meal_plan_id: string | null;
          date: string;
          breakfast_meal_id: string | null;
          lunch_meal_id: string | null;
          dinner_meal_id: string | null;
          snack_meal_id: string | null;
          total_calories: number;
          total_protein: number;
          total_carbs: number;
          total_fat: number;
          total_fiber: number;
          mood: 'poor' | 'fair' | 'good' | 'excellent' | null;
          energy_level: 1 | 2 | 3 | 4 | 5 | null;
          hunger_level: 1 | 2 | 3 | 4 | 5 | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          meal_plan_id?: string | null;
          date: string;
          breakfast_meal_id?: string | null;
          lunch_meal_id?: string | null;
          dinner_meal_id?: string | null;
          snack_meal_id?: string | null;
          total_calories?: number;
          total_protein?: number;
          total_carbs?: number;
          total_fat?: number;
          total_fiber?: number;
          mood?: 'poor' | 'fair' | 'good' | 'excellent' | null;
          energy_level?: 1 | 2 | 3 | 4 | 5 | null;
          hunger_level?: 1 | 2 | 3 | 4 | 5 | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          meal_plan_id?: string | null;
          date?: string;
          breakfast_meal_id?: string | null;
          lunch_meal_id?: string | null;
          dinner_meal_id?: string | null;
          snack_meal_id?: string | null;
          total_calories?: number;
          total_protein?: number;
          total_carbs?: number;
          total_fat?: number;
          total_fiber?: number;
          mood?: 'poor' | 'fair' | 'good' | 'excellent' | null;
          energy_level?: 1 | 2 | 3 | 4 | 5 | null;
          hunger_level?: 1 | 2 | 3 | 4 | 5 | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      social_events: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          event_date: string;
          event_type: 'restaurant' | 'dinner_party' | 'celebration' | 'family_gathering' | 'other';
          location: string | null;
          expected_meal_count: number;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          event_date: string;
          event_type: 'restaurant' | 'dinner_party' | 'celebration' | 'family_gathering' | 'other';
          location?: string | null;
          expected_meal_count?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          event_date?: string;
          event_type?: 'restaurant' | 'dinner_party' | 'celebration' | 'family_gathering' | 'other';
          location?: string | null;
          expected_meal_count?: number;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      reset_history: {
        Row: {
          id: string;
          user_id: string;
          reset_date: string;
          reason: string | null;
          previous_plan_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          reset_date: string;
          reason?: string | null;
          previous_plan_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          reset_date?: string;
          reason?: string | null;
          previous_plan_id?: string | null;
          created_at?: string;
        };
      };
      swap_history: {
        Row: {
          id: string;
          user_id: string;
          date: string;
          meal_slot: 'breakfast' | 'lunch' | 'dinner' | 'snack';
          original_meal_id: string;
          new_meal_id: string;
          reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          date: string;
          meal_slot: 'breakfast' | 'lunch' | 'dinner' | 'snack';
          original_meal_id: string;
          new_meal_id: string;
          reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          date?: string;
          meal_slot?: 'breakfast' | 'lunch' | 'dinner' | 'snack';
          original_meal_id?: string;
          new_meal_id?: string;
          reason?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};
