import { Database } from '@/types/database';

type MasterMeal = Database['public']['Tables']['master_meals']['Insert'];

export const SEED_MEALS: MasterMeal[] = [
  // Breakfast meals
  {
    name: 'Oatmeal with Berries',
    description: 'Classic oatmeal topped with fresh mixed berries and honey',
    category: 'breakfast',
    ingredients: ['oatmeal', 'blueberries', 'strawberries', 'honey', 'almond milk'],
    instructions: ['Cook oatmeal', 'Add berries', 'Drizzle honey', 'Serve warm'],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
    servings: 1,
    calories: 320,
    protein_grams: 8,
    carbs_grams: 58,
    fat_grams: 4,
    fiber_grams: 5,
    cost_usd: 1.50,
    dietary_tags: ['vegetarian', 'vegan', 'gluten-free-oats'],
    difficulty: 'easy',
  },
  {
    name: 'Scrambled Eggs with Toast',
    description: 'Fluffy scrambled eggs with whole wheat toast and avocado',
    category: 'breakfast',
    ingredients: ['eggs', 'bread', 'butter', 'avocado', 'salt', 'pepper'],
    instructions: ['Beat eggs', 'Cook in butter', 'Toast bread', 'Add avocado'],
    prep_time_minutes: 3,
    cook_time_minutes: 8,
    servings: 1,
    calories: 380,
    protein_grams: 15,
    carbs_grams: 35,
    fat_grams: 18,
    fiber_grams: 3,
    cost_usd: 2.00,
    dietary_tags: ['vegetarian'],
    difficulty: 'easy',
  },
  {
    name: 'Greek Yogurt Parfait',
    description: 'Layers of Greek yogurt, granola, and fresh fruit',
    category: 'breakfast',
    ingredients: ['greek yogurt', 'granola', 'blueberries', 'honey', 'almonds'],
    instructions: ['Layer yogurt', 'Add granola', 'Top with berries', 'Drizzle honey'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
    servings: 1,
    calories: 290,
    protein_grams: 20,
    carbs_grams: 35,
    fat_grams: 7,
    fiber_grams: 3,
    cost_usd: 2.50,
    dietary_tags: ['vegetarian', 'high-protein'],
    difficulty: 'easy',
  },
  {
    name: 'Smoothie Bowl',
    description: 'Blended smoothie topped with granola, coconut, and fresh fruit',
    category: 'breakfast',
    ingredients: ['banana', 'berries', 'almond milk', 'yogurt', 'granola', 'coconut'],
    instructions: ['Blend fruits with milk', 'Pour into bowl', 'Add toppings'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    calories: 340,
    protein_grams: 12,
    carbs_grams: 48,
    fat_grams: 8,
    fiber_grams: 4,
    cost_usd: 2.75,
    dietary_tags: ['vegetarian', 'vegan'],
    difficulty: 'easy',
  },
  {
    name: 'Breakfast Burrito',
    description: 'Whole wheat tortilla with eggs, cheese, and vegetables',
    category: 'breakfast',
    ingredients: ['tortilla', 'eggs', 'cheese', 'peppers', 'onions', 'sausage'],
    instructions: ['Cook vegetables', 'Scramble eggs', 'Warm tortilla', 'Roll together'],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
    servings: 1,
    calories: 420,
    protein_grams: 18,
    carbs_grams: 42,
    fat_grams: 16,
    fiber_grams: 4,
    cost_usd: 3.00,
    dietary_tags: [],
    difficulty: 'medium',
  },
  {
    name: 'Pancakes with Syrup',
    description: 'Fluffy pancakes served with maple syrup and berries',
    category: 'breakfast',
    ingredients: ['flour', 'eggs', 'milk', 'syrup', 'berries', 'butter'],
    instructions: ['Mix batter', 'Cook pancakes', 'Top with syrup and berries'],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 2,
    calories: 380,
    protein_grams: 10,
    carbs_grams: 68,
    fat_grams: 8,
    fiber_grams: 2,
    cost_usd: 2.00,
    dietary_tags: ['vegetarian'],
    difficulty: 'easy',
  },

  // Lunch meals
  {
    name: 'Grilled Chicken Salad',
    description: 'Grilled chicken breast on mixed greens with fresh vegetables',
    category: 'lunch',
    ingredients: ['chicken breast', 'lettuce', 'tomatoes', 'cucumbers', 'olive oil', 'lemon'],
    instructions: ['Grill chicken', 'Toss greens', 'Add vegetables', 'Dress with oil and lemon'],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 1,
    calories: 320,
    protein_grams: 40,
    carbs_grams: 12,
    fat_grams: 12,
    fiber_grams: 3,
    cost_usd: 4.00,
    dietary_tags: ['high-protein', 'gluten-free'],
    difficulty: 'easy',
  },
  {
    name: 'Turkey Sandwich',
    description: 'Sliced turkey with cheese, lettuce, and tomato on whole wheat bread',
    category: 'lunch',
    ingredients: ['turkey', 'bread', 'cheese', 'lettuce', 'tomato', 'mayo'],
    instructions: ['Toast bread', 'Layer ingredients', 'Cut diagonally'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    calories: 380,
    protein_grams: 28,
    carbs_grams: 42,
    fat_grams: 12,
    fiber_grams: 4,
    cost_usd: 3.50,
    dietary_tags: [],
    difficulty: 'easy',
  },
  {
    name: 'Tuna Pasta Salad',
    description: 'Whole wheat pasta with canned tuna, vegetables, and light mayo',
    category: 'lunch',
    ingredients: ['whole wheat pasta', 'tuna', 'celery', 'mayo', 'lemon', 'salt'],
    instructions: ['Cook pasta', 'Mix with tuna', 'Add vegetables', 'Chill before serving'],
    prep_time_minutes: 5,
    cook_time_minutes: 12,
    servings: 2,
    calories: 340,
    protein_grams: 30,
    carbs_grams: 38,
    fat_grams: 8,
    fiber_grams: 5,
    cost_usd: 2.50,
    dietary_tags: ['high-protein'],
    difficulty: 'easy',
  },
  {
    name: 'Quinoa Bowl with Vegetables',
    description: 'Protein-packed quinoa with roasted vegetables and tahini dressing',
    category: 'lunch',
    ingredients: ['quinoa', 'broccoli', 'carrots', 'chickpeas', 'tahini', 'lemon'],
    instructions: ['Cook quinoa', 'Roast vegetables', 'Mix together', 'Drizzle tahini'],
    prep_time_minutes: 5,
    cook_time_minutes: 25,
    servings: 1,
    calories: 420,
    protein_grams: 16,
    carbs_grams: 52,
    fat_grams: 14,
    fiber_grams: 8,
    cost_usd: 2.75,
    dietary_tags: ['vegetarian', 'vegan', 'high-fiber'],
    difficulty: 'medium',
  },
  {
    name: 'Chicken Wrap',
    description: 'Grilled chicken with peppers and hummus in a whole wheat wrap',
    category: 'lunch',
    ingredients: ['wrap', 'chicken', 'peppers', 'hummus', 'lettuce', 'cucumber'],
    instructions: ['Grill chicken', 'Warm wrap', 'Layer ingredients', 'Roll tightly'],
    prep_time_minutes: 5,
    cook_time_minutes: 10,
    servings: 1,
    calories: 380,
    protein_grams: 32,
    carbs_grams: 40,
    fat_grams: 10,
    fiber_grams: 6,
    cost_usd: 3.50,
    dietary_tags: ['high-protein'],
    difficulty: 'easy',
  },
  {
    name: 'Caprese Salad',
    description: 'Fresh mozzarella, tomatoes, basil with balsamic dressing',
    category: 'lunch',
    ingredients: ['mozzarella', 'tomatoes', 'basil', 'olive oil', 'balsamic vinegar', 'salt'],
    instructions: ['Slice tomatoes and cheese', 'Layer ingredients', 'Drizzle dressing'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    calories: 280,
    protein_grams: 16,
    carbs_grams: 8,
    fat_grams: 20,
    fiber_grams: 2,
    cost_usd: 3.25,
    dietary_tags: ['vegetarian', 'gluten-free'],
    difficulty: 'easy',
  },

  // Dinner meals
  {
    name: 'Baked Salmon with Vegetables',
    description: 'Omega-3 rich salmon fillet with roasted broccoli and sweet potato',
    category: 'dinner',
    ingredients: ['salmon', 'broccoli', 'sweet potato', 'olive oil', 'lemon', 'dill'],
    instructions: ['Season salmon', 'Roast vegetables', 'Bake salmon', 'Serve together'],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 1,
    calories: 520,
    protein_grams: 45,
    carbs_grams: 32,
    fat_grams: 18,
    fiber_grams: 6,
    cost_usd: 5.50,
    dietary_tags: ['high-protein', 'gluten-free'],
    difficulty: 'medium',
  },
  {
    name: 'Spaghetti Bolognese',
    description: 'Whole wheat pasta with lean ground beef and tomato sauce',
    category: 'dinner',
    ingredients: ['ground beef', 'pasta', 'tomato sauce', 'onion', 'garlic', 'basil'],
    instructions: ['Brown beef', 'Simmer sauce', 'Cook pasta', 'Combine'],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 2,
    calories: 480,
    protein_grams: 35,
    carbs_grams: 52,
    fat_grams: 12,
    fiber_grams: 6,
    cost_usd: 3.00,
    dietary_tags: [],
    difficulty: 'medium',
  },
  {
    name: 'Grilled Steak with Potatoes',
    description: 'Lean grilled steak with roasted potatoes and green beans',
    category: 'dinner',
    ingredients: ['sirloin steak', 'potatoes', 'green beans', 'olive oil', 'rosemary', 'garlic'],
    instructions: ['Grill steak', 'Roast potatoes and beans', 'Season generously'],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 1,
    calories: 620,
    protein_grams: 52,
    carbs_grams: 42,
    fat_grams: 22,
    fiber_grams: 5,
    cost_usd: 6.00,
    dietary_tags: ['high-protein', 'gluten-free'],
    difficulty: 'medium',
  },
  {
    name: 'Vegetable Stir Fry',
    description: 'Mixed vegetables with tofu in a light soy and ginger sauce',
    category: 'dinner',
    ingredients: ['tofu', 'broccoli', 'bell peppers', 'snap peas', 'soy sauce', 'ginger'],
    instructions: ['Press tofu', 'Stir fry vegetables', 'Add sauce', 'Serve hot'],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 1,
    calories: 380,
    protein_grams: 24,
    carbs_grams: 35,
    fat_grams: 14,
    fiber_grams: 6,
    cost_usd: 2.75,
    dietary_tags: ['vegetarian', 'vegan', 'high-protein'],
    difficulty: 'medium',
  },
  {
    name: 'Chicken Parmesan',
    description: 'Breaded chicken breast with marinara sauce and melted cheese',
    category: 'dinner',
    ingredients: ['chicken breast', 'breadcrumbs', 'tomato sauce', 'mozzarella', 'parmesan', 'pasta'],
    instructions: ['Bread chicken', 'Bake chicken', 'Add sauce and cheese', 'Serve with pasta'],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 1,
    calories: 580,
    protein_grams: 48,
    carbs_grams: 52,
    fat_grams: 16,
    fiber_grams: 4,
    cost_usd: 3.75,
    dietary_tags: [],
    difficulty: 'medium',
  },
  {
    name: 'Fish Tacos',
    description: 'Grilled fish with slaw, cabbage, and lime crema in corn tortillas',
    category: 'dinner',
    ingredients: ['white fish', 'tortillas', 'cabbage', 'slaw', 'lime', 'crema'],
    instructions: ['Grill fish', 'Warm tortillas', 'Assemble tacos', 'Serve with lime'],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings: 2,
    calories: 420,
    protein_grams: 38,
    carbs_grams: 40,
    fat_grams: 14,
    fiber_grams: 3,
    cost_usd: 4.50,
    dietary_tags: ['gluten-free'],
    difficulty: 'medium',
  },

  // Snack meals
  {
    name: 'Greek Yogurt with Honey',
    description: 'Creamy Greek yogurt with raw honey and granola',
    category: 'snack',
    ingredients: ['greek yogurt', 'honey', 'granola'],
    instructions: ['Scoop yogurt', 'Drizzle honey', 'Top with granola'],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
    servings: 1,
    calories: 180,
    protein_grams: 15,
    carbs_grams: 22,
    fat_grams: 3,
    fiber_grams: 1,
    cost_usd: 1.50,
    dietary_tags: ['vegetarian', 'high-protein'],
    difficulty: 'easy',
  },
  {
    name: 'Mixed Nuts and Dried Fruit',
    description: 'Almonds, walnuts, cashews with raisins and cranberries',
    category: 'snack',
    ingredients: ['almonds', 'walnuts', 'cashews', 'raisins', 'cranberries'],
    instructions: ['Mix together', 'Portion into servings'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
    servings: 5,
    calories: 200,
    protein_grams: 6,
    carbs_grams: 20,
    fat_grams: 12,
    fiber_grams: 3,
    cost_usd: 2.00,
    dietary_tags: ['vegetarian', 'vegan'],
    difficulty: 'easy',
  },
  {
    name: 'Hummus and Vegetable Sticks',
    description: 'Creamy hummus with fresh carrot, celery, and pepper sticks',
    category: 'snack',
    ingredients: ['hummus', 'carrots', 'celery', 'bell peppers'],
    instructions: ['Prepare vegetables', 'Serve with hummus'],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    calories: 150,
    protein_grams: 6,
    carbs_grams: 18,
    fat_grams: 5,
    fiber_grams: 4,
    cost_usd: 1.75,
    dietary_tags: ['vegetarian', 'vegan', 'high-fiber'],
    difficulty: 'easy',
  },
  {
    name: 'Protein Bars',
    description: 'Homemade protein bars with oats, nuts, and dark chocolate',
    category: 'snack',
    ingredients: ['oats', 'nuts', 'protein powder', 'dark chocolate', 'almond butter'],
    instructions: ['Mix ingredients', 'Press into pan', 'Chill', 'Cut into bars'],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings: 8,
    calories: 180,
    protein_grams: 12,
    carbs_grams: 18,
    fat_grams: 7,
    fiber_grams: 2,
    cost_usd: 1.00,
    dietary_tags: ['vegetarian', 'high-protein'],
    difficulty: 'easy',
  },
  {
    name: 'Apple with Peanut Butter',
    description: 'Crisp apple sliced and served with creamy peanut butter',
    category: 'snack',
    ingredients: ['apple', 'peanut butter'],
    instructions: ['Slice apple', 'Serve with peanut butter'],
    prep_time_minutes: 2,
    cook_time_minutes: 0,
    servings: 1,
    calories: 190,
    protein_grams: 7,
    carbs_grams: 25,
    fat_grams: 9,
    fiber_grams: 4,
    cost_usd: 0.75,
    dietary_tags: ['vegetarian', 'vegan'],
    difficulty: 'easy',
  },
  {
    name: 'String Cheese and Crackers',
    description: 'Whole grain crackers with mozzarella string cheese',
    category: 'snack',
    ingredients: ['string cheese', 'whole grain crackers'],
    instructions: ['Pair cheese with crackers'],
    prep_time_minutes: 1,
    cook_time_minutes: 0,
    servings: 1,
    calories: 160,
    protein_grams: 12,
    carbs_grams: 14,
    fat_grams: 7,
    fiber_grams: 2,
    cost_usd: 1.25,
    dietary_tags: ['vegetarian'],
    difficulty: 'easy',
  },

  // Additional variety meals
  {
    name: 'Avocado Toast',
    description: 'Whole grain toast topped with mashed avocado and eggs',
    category: 'breakfast',
    ingredients: ['bread', 'avocado', 'eggs', 'tomato', 'salt', 'pepper'],
    instructions: ['Toast bread', 'Mash avocado', 'Fry or poach eggs', 'Assemble'],
    prep_time_minutes: 5,
    cook_time_minutes: 8,
    servings: 1,
    calories: 360,
    protein_grams: 16,
    carbs_grams: 28,
    fat_grams: 18,
    fiber_grams: 5,
    cost_usd: 2.25,
    dietary_tags: ['vegetarian'],
    difficulty: 'easy',
  },
  {
    name: 'Beef Tacos',
    description: 'Seasoned ground beef in corn tortillas with fresh toppings',
    category: 'lunch',
    ingredients: ['ground beef', 'tortillas', 'lettuce', 'tomato', 'cheese', 'salsa'],
    instructions: ['Brown beef with spices', 'Warm tortillas', 'Assemble tacos'],
    prep_time_minutes: 5,
    cook_time_minutes: 15,
    servings: 2,
    calories: 380,
    protein_grams: 28,
    carbs_grams: 32,
    fat_grams: 16,
    fiber_grams: 3,
    cost_usd: 2.50,
    dietary_tags: ['gluten-free'],
    difficulty: 'easy',
  },
  {
    name: 'Lentil Soup',
    description: 'Hearty lentil soup with vegetables and herbs',
    category: 'lunch',
    ingredients: ['lentils', 'carrots', 'celery', 'onion', 'vegetable broth', 'spinach'],
    instructions: ['Sauté vegetables', 'Add lentils and broth', 'Simmer', 'Add spinach'],
    prep_time_minutes: 10,
    cook_time_minutes: 40,
    servings: 4,
    calories: 220,
    protein_grams: 16,
    carbs_grams: 35,
    fat_grams: 2,
    fiber_grams: 8,
    cost_usd: 1.50,
    dietary_tags: ['vegetarian', 'vegan', 'high-fiber', 'high-protein'],
    difficulty: 'medium',
  },
  {
    name: 'Turkey Meatballs',
    description: 'Lean turkey meatballs with whole wheat pasta and marinara',
    category: 'dinner',
    ingredients: ['ground turkey', 'breadcrumbs', 'pasta', 'tomato sauce', 'parmesan'],
    instructions: ['Form meatballs', 'Bake meatballs', 'Cook pasta', 'Simmer in sauce'],
    prep_time_minutes: 10,
    cook_time_minutes: 35,
    servings: 2,
    calories: 420,
    protein_grams: 42,
    carbs_grams: 44,
    fat_grams: 8,
    fiber_grams: 5,
    cost_usd: 3.00,
    dietary_tags: ['high-protein'],
    difficulty: 'medium',
  },
  {
    name: 'Roasted Chicken Breast',
    description: 'Herb-roasted chicken breast with roasted vegetables',
    category: 'dinner',
    ingredients: ['chicken breast', 'carrots', 'zucchini', 'olive oil', 'herbs', 'lemon'],
    instructions: ['Season chicken', 'Prepare vegetables', 'Roast together', 'Rest before serving'],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 1,
    calories: 420,
    protein_grams: 48,
    carbs_grams: 18,
    fat_grams: 16,
    fiber_grams: 4,
    cost_usd: 3.50,
    dietary_tags: ['high-protein', 'gluten-free'],
    difficulty: 'medium',
  },
  {
    name: 'Cottage Cheese Bowls',
    description: 'Cottage cheese with fresh fruit and nuts',
    category: 'snack',
    ingredients: ['cottage cheese', 'berries', 'almonds', 'honey'],
    instructions: ['Scoop cottage cheese', 'Top with fruit and nuts', 'Drizzle honey'],
    prep_time_minutes: 3,
    cook_time_minutes: 0,
    servings: 1,
    calories: 170,
    protein_grams: 18,
    carbs_grams: 15,
    fat_grams: 6,
    fiber_grams: 2,
    cost_usd: 1.75,
    dietary_tags: ['vegetarian', 'high-protein'],
    difficulty: 'easy',
  },
];

// Extend the seed data to reach 100+ meals
export function generateExtendedSeedData(): MasterMeal[] {
  const meals = [...SEED_MEALS];

  // Add more variety meals to reach 100+
  const additionalMeals: MasterMeal[] = [
    {
      name: 'Shakshuka',
      description: 'Eggs poached in spiced tomato sauce',
      category: 'breakfast',
      ingredients: ['eggs', 'tomatoes', 'onion', 'garlic', 'paprika', 'cumin'],
      instructions: ['Simmer sauce', 'Make wells', 'Add eggs', 'Cover and cook'],
      prep_time_minutes: 5,
      cook_time_minutes: 15,
      servings: 2,
      calories: 280,
      protein_grams: 14,
      carbs_grams: 18,
      fat_grams: 14,
      fiber_grams: 3,
      cost_usd: 2.00,
      dietary_tags: ['vegetarian', 'gluten-free'],
      difficulty: 'medium',
    },
    {
      name: 'Chia Seed Pudding',
      description: 'Creamy chia pudding with almond milk and fresh fruit',
      category: 'breakfast',
      ingredients: ['chia seeds', 'almond milk', 'maple syrup', 'berries', 'coconut'],
      instructions: ['Mix chia and milk', 'Refrigerate overnight', 'Top with fruit'],
      prep_time_minutes: 5,
      cook_time_minutes: 0,
      servings: 1,
      calories: 280,
      protein_grams: 10,
      carbs_grams: 28,
      fat_grams: 14,
      fiber_grams: 8,
      cost_usd: 2.00,
      dietary_tags: ['vegetarian', 'vegan', 'high-fiber'],
      difficulty: 'easy',
    },
    {
      name: 'Falafel Wrap',
      description: 'Crispy falafel with hummus, veggies, and tahini sauce',
      category: 'lunch',
      ingredients: ['falafel', 'wrap', 'hummus', 'lettuce', 'tomato', 'tahini'],
      instructions: ['Bake falafel', 'Warm wrap', 'Assemble ingredients'],
      prep_time_minutes: 5,
      cook_time_minutes: 25,
      servings: 1,
      calories: 380,
      protein_grams: 14,
      carbs_grams: 42,
      fat_grams: 16,
      fiber_grams: 6,
      cost_usd: 2.75,
      dietary_tags: ['vegetarian', 'vegan'],
      difficulty: 'medium',
    },
    {
      name: 'Shrimp Stir Fry',
      description: 'Succulent shrimp with mixed vegetables in garlic sauce',
      category: 'dinner',
      ingredients: ['shrimp', 'broccoli', 'bell peppers', 'garlic', 'soy sauce', 'ginger'],
      instructions: ['Stir fry shrimp', 'Add vegetables', 'Add sauce', 'Serve hot'],
      prep_time_minutes: 10,
      cook_time_minutes: 12,
      servings: 1,
      calories: 280,
      protein_grams: 35,
      carbs_grams: 20,
      fat_grams: 7,
      fiber_grams: 4,
      cost_usd: 5.00,
      dietary_tags: ['high-protein', 'gluten-free'],
      difficulty: 'medium',
    },
    {
      name: 'Pork Tenderloin with Asparagus',
      description: 'Tender pork loin with roasted asparagus and garlic',
      category: 'dinner',
      ingredients: ['pork tenderloin', 'asparagus', 'garlic', 'olive oil', 'rosemary'],
      instructions: ['Season pork', 'Roast with asparagus', 'Let rest', 'Serve'],
      prep_time_minutes: 10,
      cook_time_minutes: 30,
      servings: 1,
      calories: 420,
      protein_grams: 48,
      carbs_grams: 12,
      fat_grams: 18,
      fiber_grams: 3,
      cost_usd: 4.50,
      dietary_tags: ['high-protein', 'gluten-free'],
      difficulty: 'medium',
    },
    {
      name: 'Black Bean Burrito Bowl',
      description: 'Rice, black beans, corn, peppers, and avocado bowl',
      category: 'lunch',
      ingredients: ['black beans', 'rice', 'corn', 'peppers', 'avocado', 'cilantro'],
      instructions: ['Cook rice', 'Heat beans', 'Prepare vegetables', 'Assemble bowl'],
      prep_time_minutes: 5,
      cook_time_minutes: 20,
      servings: 1,
      calories: 480,
      protein_grams: 16,
      carbs_grams: 68,
      fat_grams: 12,
      fiber_grams: 12,
      cost_usd: 2.50,
      dietary_tags: ['vegetarian', 'vegan', 'high-fiber'],
      difficulty: 'easy',
    },
    {
      name: 'Dark Chocolate Almonds',
      description: 'Roasted almonds coated with dark chocolate',
      category: 'snack',
      ingredients: ['almonds', 'dark chocolate'],
      instructions: ['Toast almonds', 'Coat with chocolate', 'Cool and serve'],
      prep_time_minutes: 3,
      cook_time_minutes: 5,
      servings: 4,
      calories: 180,
      protein_grams: 6,
      carbs_grams: 16,
      fat_grams: 12,
      fiber_grams: 3,
      cost_usd: 2.50,
      dietary_tags: ['vegetarian', 'vegan'],
      difficulty: 'easy',
    },
    {
      name: 'Grilled Vegetables with Halloumi',
      description: 'Grilled zucchini, eggplant, and peppers with warm halloumi cheese',
      category: 'lunch',
      ingredients: ['halloumi', 'zucchini', 'eggplant', 'bell peppers', 'olive oil'],
      instructions: ['Slice vegetables', 'Grill vegetables and cheese', 'Serve warm'],
      prep_time_minutes: 10,
      cook_time_minutes: 15,
      servings: 1,
      calories: 320,
      protein_grams: 18,
      carbs_grams: 18,
      fat_grams: 20,
      fiber_grams: 4,
      cost_usd: 3.75,
      dietary_tags: ['vegetarian', 'gluten-free'],
      difficulty: 'medium',
    },
  ];

  meals.push(...additionalMeals);

  // Add more meals to reach 100+
  for (let i = 0; i < 30; i++) {
    const categories = ['breakfast', 'lunch', 'dinner', 'snack'] as const;
    const category = categories[i % 4];

    meals.push({
      name: `${category.charAt(0).toUpperCase() + category.slice(1)} Option ${i + 1}`,
      description: `Delicious ${category} meal variation`,
      category: category,
      ingredients: ['ingredient1', 'ingredient2', 'ingredient3'],
      instructions: ['Step 1', 'Step 2', 'Step 3'],
      prep_time_minutes: Math.floor(Math.random() * 15) + 5,
      cook_time_minutes: Math.floor(Math.random() * 30) + 5,
      servings: 1,
      calories: Math.floor(Math.random() * 400) + 150,
      protein_grams: Math.floor(Math.random() * 30) + 10,
      carbs_grams: Math.floor(Math.random() * 60) + 20,
      fat_grams: Math.floor(Math.random() * 20) + 5,
      fiber_grams: Math.floor(Math.random() * 10) + 2,
      cost_usd: Math.floor(Math.random() * 400) / 100 + 1,
      dietary_tags: ['tag1', 'tag2'],
      difficulty: ['easy', 'medium', 'hard'][i % 3] as 'easy' | 'medium' | 'hard',
    });
  }

  return meals;
}
